[package]
name = "vulpid-tech"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "vulpid-tech"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
# Windowing
winit = "0.30"

# Graphics
glow = "0.13"

# Audio
alto = "3.0"
